# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - sjdnotes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    buildreactapp:
      runs-on:  windows-latest
      defaults:
        run:
          working-directory:  note-frontend
          shell: pwsh
      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - uses: actions/checkout@v2

        - name: Create env file
          env:
            ENV_FILE: ${{secrets.ENV_FILE}}
          run: |
           "$env:ENV_FILE" > .env
            cat .env
      
        - name: Set up Node Js
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install Dependencies
          run: |
            npm cache clean --force
            npm install

        - name: build react app
          run: npm run build  --if-present
          env:
            CI: false
        
        - name: Upload Artifact 
          uses: actions/upload-artifact@v2
          with:
            name: react-app
            path: note-frontend/build


    builddotnetapp:
      runs-on: windows-latest
      defaults:
        run:
          working-directory: NotesService
          shell: pwsh
      needs: buildreactapp
     

      steps:
        - uses: actions/checkout@v2

        - name: Setup .Net core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.x'

        - name: Build with dotnet
          run:  dotnet build --configuration Release 

        - name: Dot net publish
          run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

        - name: Download react artifact
          uses: actions/download-artifact@v2
          with:
            name: react-app
            path: ./build

        - name: Copy react app to dotnet published folder
          run:  |
            copy -Path "../build/*" -Destination "${{env.DOTNET_ROOT}}/myapp/app" -Force
            copy -Path "../build/static/css/*" -Destination "${{env.DOTNET_ROOT}}/myapp/app/static/css" -Force -Recurse
            copy -Path "../build/static/js/*" -Destination "${{env.DOTNET_ROOT}}/myapp/app/static/js" -Force -Recurse
            copy -Path "../build/static/media/*" -Destination "${{env.DOTNET_ROOT}}/myapp/app/static/media"  -Force -Recurse

        - name: Upload app for deplpoyment job
          uses: actions/upload-artifact@v2
          with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp
      
      

    deploy:
      runs-on: windows-latest
      needs: builddotnetapp
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: .net-app

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'sjdnotes'
            slot-name: 'Production'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30EE1D75117946FDA003DBC2EFCE62B2 }}
            package: .
